all:
	make -C ./snake/.
	make -C ./pacman/.

clean:
	make clean -C ./snake/.
	make clean -C ./pacman/.

fclean:
	make fclean -C ./snake/.
	make fclean -C ./pacman/.

re: 	fclean all

.PHONY: all clean fclean re
